import os
import pygame

# win
WIN_WIDTH = 1600
WIN_HEIGHT = 900

# path
IMAGE_PATH = os.path.join(os.path.dirname(__file__), "images")
NAME_PATH = os.path.join(os.path.dirname(__file__), "images/name")
PART_PATH = os.path.join(os.path.dirname(__file__), "images/part")

# background
background = pygame.transform.scale(pygame.image.load(os.path.join(IMAGE_PATH, "背景.png")), (WIN_WIDTH, WIN_HEIGHT))

# images name
name_A1 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "王伊澄.jpg")), (800, 800))
name_A2 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "王佳佳.jpg")), (800, 800))
name_A3 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "朱以恩.jpg")), (800, 800))
name_A4 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "朱芷晴.jpg")), (800, 800))
name_A5 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "江芊葳.jpg")), (800, 800))
name_A6 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "何映嫻.jpg")), (800, 800))
name_B1 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "吳帆柔.jpg")), (800, 800))
name_B2 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "吳芊葳.jpg")), (800, 800))
name_B3 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "李志宇.jpg")), (800, 800))
name_B4 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "李昀珊.jpg")), (800, 800))
name_B5 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "李易蒼.jpg")), (800, 800))
name_B6 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "林佳欣.jpg")), (800, 800))
name_C1 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "林獻晞.jpg")), (800, 800))
name_C2 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "胡文.jpg")), (800, 800))
name_C3 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "凌楷勛.jpg")), (800, 800))
name_C4 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "高培淞.jpg")), (800, 800))
name_C5 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "張毓禾.jpg")), (800, 800))
name_C6 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "梁雅喻.jpg")), (800, 800))
name_D1 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "陳怡安.jpg")), (800, 800))
name_D2 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "陳芷琦.jpg")), (800, 800))
name_D3 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "陳冠州.jpg")), (800, 800))
name_D4 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "陳鈞睿.jpg")), (800, 800))
name_D5 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "曾偉傑.jpg")), (800, 800))
name_D6 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "馮禮君.jpg")), (800, 800))
name_E1 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "黃茂軒.jpg")), (800, 800))
name_E2 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "黃容羽.jpg")), (800, 800))
name_E3 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "黃椅琪.jpg")), (800, 800))
name_E4 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "楊致遠.jpg")), (800, 800))
name_E5 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "廖婕妤.jpg")), (800, 800))
name_E6 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "劉佩沂.jpg")), (800, 800))
name_F1 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "蔡兆寧.jpg")), (800, 800))
name_F2 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "蔡震暘.jpg")), (800, 800))
name_F3 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "鄭羽珊.jpg")), (800, 800))
name_F4 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "盧郁禎.jpg")), (800, 800))
name_F5 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "賴奕綜.jpg")), (800, 800))
name_F6 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "鍾志豪.jpg")), (800, 800))
name_G1 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "羅兆男.jpg")), (800, 800))
name_G2 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "羅逸軒.jpg")), (800, 800))
name_G3 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "龔怡安.jpg")), (800, 800))
'''name_G4 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "朱芷晴.jpg")), (500, 450))
name_G5 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "江芊葳.jpg")), (500, 450))
name_G6 = pygame.transform.scale(pygame.image.load(os.path.join(NAME_PATH, "何映嫻.jpg")), (500, 450))'''

# image part
part_A1 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "王伊澄.jpg")), (100, 47))
part_A2 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "王佳佳.jpg")), (100, 50))
part_A3 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "朱以恩.jpg")), (100, 31))
part_A4 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "朱芷晴.jpg")), (100, 38))
part_A5 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "江芊葳.jpg")), (100, 25))
part_A6 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "何映嫻.jpg")), (100, 33))
part_B1 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "吳帆柔.jpg")), (100, 38))
part_B2 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "吳芊葳.jpg")), (100, 41))
part_B3 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "李志宇.jpg")), (100, 31))
part_B4 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "李昀珊.jpg")), (100, 47))
part_B5 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "李易蒼.jpg")), (100, 95))
part_B6 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "林佳欣.jpg")), (100, 47))
part_C1 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "林獻晞.jpg")), (100, 44))
part_C2 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "胡文.jpg")), (100, 48))
part_C3 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "凌楷勛.jpg")), (100, 25))
part_C4 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "高培淞.jpg")), (100, 89))
part_C5 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "張毓禾.jpg")), (100, 39))
part_C6 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "梁雅喻.jpg")), (100, 43))
part_D1 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "陳怡安.jpg")), (100, 34))
part_D2 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "陳芷琦.jpg")), (100, 34))
part_D3 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "陳冠州.jpg")), (100, 39))
part_D4 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "陳鈞睿.jpg")), (100, 33))
part_D5 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "曾偉傑.jpg")), (100, 43))
part_D6 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "馮禮君.jpg")), (100, 59))
part_E1 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "黃茂軒.jpg")), (100, 100))
part_E2 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "黃容羽.jpg")), (100, 38))
part_E3 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "黃椅琪.jpg")), (100, 34))
part_E4 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "楊致遠.jpg")), (100, 30))
part_E5 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "廖婕妤.jpg")), (100, 26))
part_E6 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "劉佩沂.jpg")), (100, 56))
part_F1 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "蔡兆寧.jpg")), (100, 43))
part_F2 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "蔡震暘.jpg")), (100, 48))
part_F3 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "鄭羽珊.jpg")), (100, 77))
part_F4 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "盧郁禎.jpg")), (100, 32))
part_F5 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "賴奕綜.jpg")), (100, 25))
part_F6 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "鍾志豪.jpg")), (100, 46))
part_G1 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "羅兆男.jpg")), (100, 44))
part_G2 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "羅逸軒.jpg")), (100, 54))
part_G3 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "龔怡安.jpg")), (100, 28))
'''part_G4 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "朱芷晴.jpg")), (70, 70))
part_G5 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "江芊葳.jpg")), (70, 70))
part_G6 = pygame.transform.scale(pygame.image.load(os.path.join(PART_PATH, "何映嫻.jpg")), (70, 70))'''
